Added NodeJS Service for MESH File Generation & Storage
PSUCompBio/aws-config pull request #9
Opened 2019-08-03 14:18 UTC by vradars

2019-08-04 13:16 UTC, rhk12 commented on docker_scripts/bash_scripts/install-pygem.sh
> +git clone https://github.com/vradars/PyGeM.git
change this to PSUCompbio

2019-08-04 13:18 UTC, rhk12 commented on docker_scripts/bash_scripts/install-rbf-brain-nodejs-service.sh
> +git clone https://github.com/vradars/rbf-brain-nodejs-service.git
needs to be changed to PSUcompbio git

2019-08-04 13:19 UTC, rhk12 requested changes
@vradars I requested some changes to the git directories

2019-08-13 07:49 UTC, vradars commented on docker_scripts/bash_scripts/install-rbf-brain-nodejs-service.sh
> +git clone https://github.com/vradars/rbf-brain-nodejs-service.git
Please fork the above repository in PSUCompBio Account.

2019-08-13 14:58 UTC, rhk12 commented on docker_scripts/bash_scripts/install-rbf-brain-nodejs-service.sh
> +git clone https://github.com/vradars/rbf-brain-nodejs-service.git
@vradars  I forked rbf-brain-node-js into PSUCompBio Account

2019-08-13 15:00 UTC, rhk12 commented on docker_scripts/bash_scripts/install-pygem.sh
> +git clone https://github.com/vradars/PyGeM.git
@vradars Since I already have this I don't want to fork it. Can you do a pull request in the PSUCompBio/PyGem repo? https://github.com/PSUCompBio/PyGeM 

You might have done this already, I can't remember.

2019-08-14 13:09 UTC, closed without merging